name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Start Minikube
    - name: Start Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker

    # Enable Ingress addon
    - name: Enable Ingress
      run: |
        minikube addons enable ingress
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=300s

    # Install Helm
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'

    # Build Docker image inside Minikube
    - name: Build Docker image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t rick-morty-service:latest .

    # Deploy using Helm
    - name: Deploy with Helm
      run: |
        helm install rick-morty ./helm/rick-morty-chart
        kubectl rollout status deployment/rick-morty-rick-morty --timeout=300s

    # Test deployed endpoints
    - name: Test deployed endpoints
      run: |
        # Wait for service and ingress to be ready
        kubectl wait --for=condition=ready pod -l app=rick-morty-service --timeout=300s
        
        # Debug information
        echo "--- Debug Info ---"
        kubectl get pods -A
        kubectl get svc -A
        kubectl get ingress -A
        
        # Get Minikube IP
        MINIKUBE_IP=$(minikube ip)
        echo "Minikube IP: $MINIKUBE_IP"
        
        # Add host entry and verify
        echo "$MINIKUBE_IP rick-morty.local" | sudo tee -a /etc/hosts
        cat /etc/hosts
        
        # Wait for ingress to be ready and get its address
        kubectl wait --for=condition=ready ingress/rick-morty-rick-morty --timeout=300s
        INGRESS_IP=$(kubectl get ingress rick-morty-rick-morty -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "Ingress IP: $INGRESS_IP"
        
        echo "--- Testing Endpoints ---"
        # Test with both IPs to debug
        for ip in $MINIKUBE_IP $INGRESS_IP; do
          echo "Testing with IP: $ip"
          curl -v -H "Host: rick-morty.local" http://$ip/healthcheck
          curl -v -H "Host: rick-morty.local" http://$ip/characters
        done
